/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/old_computers.glb -t -o components/3d/OldComputersModel.tsx 
Author: Rafael Rodrigues (https://sketchfab.com/RafaelBR873D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-computers-7bb6e720499a467b8e0427451d180063
Title: Old Computers
*/

import * as THREE from 'three'
import React, { useMemo } from 'react'
import { useGLTF, useAnimations, useTexture } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

function normalizeUVs(geometry: THREE.BufferGeometry, flipU = false): THREE.BufferGeometry {
  const cloned = geometry.clone()
  const uvAttr = cloned.getAttribute('uv') as THREE.BufferAttribute
  if (!uvAttr) return cloned

  const uvArray = new Float32Array(uvAttr.array as Float32Array)
  let minU = Infinity, maxU = -Infinity, minV = Infinity, maxV = -Infinity

  for (let i = 0; i < uvArray.length; i += 2) {
    minU = Math.min(minU, uvArray[i])
    maxU = Math.max(maxU, uvArray[i])
    minV = Math.min(minV, uvArray[i + 1])
    maxV = Math.max(maxV, uvArray[i + 1])
  }

  const rangeU = maxU - minU || 1
  const rangeV = maxV - minV || 1

  for (let i = 0; i < uvArray.length; i += 2) {
    let u = (uvArray[i] - minU) / rangeU
    const v = (uvArray[i + 1] - minV) / rangeV
    if (flipU) u = 1 - u
    uvArray[i] = u
    uvArray[i + 1] = 1 - v
  }

  cloned.setAttribute('uv', new THREE.BufferAttribute(uvArray, 2))
  return cloned
}

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_58: THREE.Mesh
    Object_60: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
    Object_66: THREE.Mesh
    Object_68: THREE.Mesh
    Object_70: THREE.Mesh
    Object_72: THREE.Mesh
    Object_74: THREE.Mesh
    Object_76: THREE.Mesh
    Object_78: THREE.Mesh
    Object_80: THREE.Mesh
    Object_82: THREE.Mesh
    Object_84: THREE.Mesh
    Object_86: THREE.Mesh
    Object_88: THREE.Mesh
    Object_90: THREE.Mesh
    Object_92: THREE.Mesh
    Object_94: THREE.Mesh
    Object_96: THREE.Mesh
    Object_98: THREE.Mesh
    Object_100: THREE.Mesh
    Object_102: THREE.Mesh
    Object_104: THREE.Mesh
    Object_106: THREE.Mesh
    Object_108: THREE.Mesh
    Object_110: THREE.Mesh
    Object_112: THREE.Mesh
    Object_114: THREE.Mesh
    Object_116: THREE.Mesh
    Object_118: THREE.Mesh
    Object_120: THREE.Mesh
    Object_122: THREE.Mesh
    Object_124: THREE.Mesh
    Object_126: THREE.Mesh
    Object_128: THREE.Mesh
    Object_130: THREE.Mesh
    Object_132: THREE.Mesh
    Object_134: THREE.Mesh
    Object_136: THREE.Mesh
    Object_138: THREE.Mesh
    Object_140: THREE.Mesh
    Object_142: THREE.Mesh
    Object_144: THREE.Mesh
    Object_146: THREE.Mesh
    Object_148: THREE.Mesh
    Object_150: THREE.Mesh
    Object_152: THREE.Mesh
    Object_154: THREE.Mesh
    Object_156: THREE.Mesh
    Object_158: THREE.Mesh
    Object_160: THREE.Mesh
    Object_162: THREE.Mesh
    Object_164: THREE.Mesh
    Object_166: THREE.Mesh
    Object_168: THREE.Mesh
    Object_170: THREE.Mesh
    Object_172: THREE.Mesh
    Object_174: THREE.Mesh
    Object_176: THREE.Mesh
    Object_178: THREE.Mesh
    Object_180: THREE.Mesh
    Object_182: THREE.Mesh
    Object_184: THREE.Mesh
    Object_186: THREE.Mesh
    Object_188: THREE.Mesh
    Object_190: THREE.Mesh
    Object_192: THREE.Mesh
    Object_194: THREE.Mesh
    Object_196: THREE.Mesh
    Object_198: THREE.Mesh
    Object_200: THREE.Mesh
    Object_202: THREE.Mesh
    Object_204: THREE.Mesh
    Object_206: THREE.Mesh
    Object_207: THREE.Mesh
    Object_209: THREE.Mesh
    Object_210: THREE.Mesh
    Object_212: THREE.Mesh
    Object_213: THREE.Mesh
    Object_215: THREE.Mesh
    Object_216: THREE.Mesh
    Object_218: THREE.Mesh
    Object_219: THREE.Mesh
    Object_221: THREE.Mesh
    Object_222: THREE.Mesh
    Object_224: THREE.Mesh
    Object_225: THREE.Mesh
    Object_227: THREE.Mesh
    Object_228: THREE.Mesh
    Object_230: THREE.Mesh
    Object_231: THREE.Mesh
  }
  materials: {
    Texture: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    Screen: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export interface SingleScreenSettings {
  enabled: boolean
  scale: number
  posX: number
  posY: number
  glow: number
}

export const SCREEN_LABELS = [
  'Center Bottom',
  'Left Mid',
  'Far Left Bottom',
  'Right Bottom',
  'Right Mid',
  'Far Left Mid',
  'Far Left Top',
  'Center Top',
  'Right Top',
]

export const DEFAULT_SCREEN: SingleScreenSettings = {
  enabled: true,
  scale: 1,
  posX: 0,
  posY: 0,
  glow: 1.2,
}


const SCREEN_NODES = [
  'Object_207', 'Object_210', 'Object_213', 'Object_216',
  'Object_219', 'Object_222', 'Object_225', 'Object_228', 'Object_231',
] as const


const MIRRORED_SCREENS = new Set([7])

export function Model({ texColor = '#ffffff', screenColor = '#ffffff', animIndex = 0, perScreenSettings, ...props }: any) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/old_computers.glb') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  const screenImage = useTexture('/images/screen_display.png')

  const screenGeometries = useMemo(() => {
    return SCREEN_NODES.map((nodeName, idx) => {
      const mesh = nodes[nodeName] as THREE.Mesh
      return normalizeUVs(mesh.geometry, MIRRORED_SCREENS.has(idx))
    })
  }, [nodes])

  const screenMaterials = useMemo(() => {
    return SCREEN_LABELS.map(() => {
      const tex = screenImage.clone()
      tex.flipY = false
      tex.colorSpace = THREE.SRGBColorSpace
      tex.wrapS = THREE.ClampToEdgeWrapping
      tex.wrapT = THREE.ClampToEdgeWrapping
      tex.minFilter = THREE.LinearFilter
      tex.magFilter = THREE.LinearFilter
      tex.needsUpdate = true

      return new THREE.MeshStandardMaterial({
        map: tex,
        emissiveMap: tex,
        emissive: new THREE.Color(0xffffff),
        emissiveIntensity: 1.2,
        toneMapped: false,
        side: THREE.DoubleSide,
      })
    })
  }, [screenImage])

  React.useEffect(() => {
    if (!perScreenSettings) return
    screenMaterials.forEach((mat, idx) => {
      const s: SingleScreenSettings = perScreenSettings[idx] || DEFAULT_SCREEN
      const tex = mat.map as THREE.Texture
      if (tex) {
        tex.repeat.set(s.scale, s.scale)
        tex.offset.set(s.posX, s.posY)
        tex.needsUpdate = true
      }
      mat.emissiveIntensity = s.glow
      mat.needsUpdate = true
    })
  }, [perScreenSettings, screenMaterials])

  React.useEffect(() => {
    if (actions) {
      const actionNames = Object.keys(actions)
      if (actionNames.length > 0) {
        Object.values(actions).forEach(action => action?.stop())

        const selectedAnim = actionNames[animIndex] || actionNames[0]
        actions[selectedAnim]?.reset().fadeIn(0.5).play()
      }
    }
  }, [actions, animIndex])

  const settings: SingleScreenSettings[] = perScreenSettings || SCREEN_LABELS.map(() => DEFAULT_SCREEN)
  const getMat = (idx: number) => settings[idx]?.enabled ? screenMaterials[idx] : materials.Screen

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.27, 1.529, -2.613]}>
        <mesh geometry={nodes.Object_206.geometry} material={materials.Texture} material-color={texColor} />
        <mesh geometry={settings[0]?.enabled ? screenGeometries[0] : nodes.Object_207.geometry} material={getMat(0)} material-color={settings[0]?.enabled ? undefined : screenColor} />
      </group>
      <group position={[-1.43, 2.496, -1.8]} rotation={[0, 1.002, 0]}>
        <mesh geometry={nodes.Object_209.geometry} material={materials.Texture} material-color={texColor} />
        <mesh geometry={settings[1]?.enabled ? screenGeometries[1] : nodes.Object_210.geometry} material={getMat(1)} material-color={settings[1]?.enabled ? undefined : screenColor} />
      </group>
      <group position={[-2.731, 0.629, -0.522]} rotation={[0, 1.087, 0]}>
        <mesh geometry={nodes.Object_212.geometry} material={materials.Texture} material-color={texColor} />
        <mesh geometry={settings[2]?.enabled ? screenGeometries[2] : nodes.Object_213.geometry} material={getMat(2)} material-color={settings[2]?.enabled ? undefined : screenColor} />
      </group>
      <group position={[1.845, 0.377, -1.771]} rotation={[0, -Math.PI / 9, 0]}>
        <mesh geometry={nodes.Object_215.geometry} material={materials.Texture} material-color={texColor} />
        <mesh geometry={settings[3]?.enabled ? screenGeometries[3] : nodes.Object_216.geometry} material={getMat(3)} material-color={settings[3]?.enabled ? undefined : screenColor} />
      </group>
      <group position={[3.11, 2.145, -0.18]} rotation={[0, -0.793, 0]} scale={0.81}>
        <mesh geometry={nodes.Object_218.geometry} material={materials.Texture} material-color={texColor} />
        <mesh geometry={settings[4]?.enabled ? screenGeometries[4] : nodes.Object_219.geometry} material={getMat(4)} material-color={settings[4]?.enabled ? undefined : screenColor} />
      </group>
      <group position={[-3.417, 3.056, 1.303]} rotation={[0, 1.222, 0]} scale={0.9}>
        <mesh geometry={nodes.Object_221.geometry} material={materials.Texture} material-color={texColor} />
        <mesh geometry={settings[5]?.enabled ? screenGeometries[5] : nodes.Object_222.geometry} material={getMat(5)} material-color={settings[5]?.enabled ? undefined : screenColor} />
      </group>
      <group position={[-3.899, 4.287, -2.642]} rotation={[0, 0.539, 0]}>
        <mesh geometry={nodes.Object_224.geometry} material={materials.Texture} material-color={texColor} />
        <mesh geometry={settings[6]?.enabled ? screenGeometries[6] : nodes.Object_225.geometry} material={getMat(6)} material-color={settings[6]?.enabled ? undefined : screenColor} />
      </group>
      <group position={[0.992, 4.287, -4.209]} rotation={[0, 0.429, 0]} scale={[-1, 1, 1]}>
        <mesh geometry={nodes.Object_227.geometry} material={materials.Texture} material-color={texColor} />
        <mesh geometry={settings[7]?.enabled ? screenGeometries[7] : nodes.Object_228.geometry} material={getMat(7)} material-color={settings[7]?.enabled ? undefined : screenColor} />
      </group>
      <group position={[4.683, 4.29, -1.558]} rotation={[0, -Math.PI / 3, 0]}>
        <mesh geometry={nodes.Object_230.geometry} material={materials.Texture} material-color={texColor} />
        <mesh geometry={settings[8]?.enabled ? screenGeometries[8] : nodes.Object_231.geometry} material={getMat(8)} material-color={settings[8]?.enabled ? undefined : screenColor} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Texture} material-color={texColor} position={[0.165, 0.794, -1.972]} rotation={[-0.544, 0.929, -1.119]} scale={0.5} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Texture} material-color={texColor} position={[-2.793, 0.27, 1.816]} rotation={[-1.44, 1.219, 1.432]} scale={0.5} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Texture} material-color={texColor} position={[-5.603, 4.615, -0.027]} rotation={[-1.955, 0.163, 1.202]} scale={0.5} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Texture} material-color={texColor} position={[2.621, 1.985, -2.473]} rotation={[-0.419, -0.704, -1.851]} scale={0.5} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Texture} material-color={texColor} position={[4.598, 3.459, 1.19]} rotation={[-1.236, -0.719, 0.48]} scale={0.5} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.001']} scale={13} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Texture} position={[0.63, 0, -3]} rotation={[0, 0.17, 0]} scale={1.52} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Texture} position={[-0.186, 0, -2.962]} rotation={[0, -0.064, 0]} scale={1.52} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Texture} position={[-2.36, 0.32, -2.018]} rotation={[0, 0.534, -Math.PI / 2]} scale={1.52} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Texture} position={[-2.288, 1.56, -2.263]} rotation={[0, -0.012, -Math.PI / 2]} scale={1.52} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Texture} position={[-2.424, 0.938, -2.247]} rotation={[Math.PI, -0.136, -Math.PI / 2]} scale={[-1.52, 1.52, 1.52]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Texture} position={[-2.195, 2.188, -1.867]} rotation={[Math.PI, -0.512, -Math.PI / 2]} scale={[-1.52, 1.52, 1.52]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.Texture} position={[0.353, 2.352, -3.336]} rotation={[-0.255, 0, 0]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Texture} position={[0.183, 2.801, -2.854]} rotation={[0.093, 0.146, -0.014]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.Texture} position={[-3.528, 0, 0.586]} rotation={[Math.PI, -1.085, Math.PI]} scale={1.52} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Texture} position={[-2.896, 0.3, -1.466]} rotation={[Math.PI, -1.347, Math.PI / 2]} scale={1.52} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.Texture} position={[-3.528, 1.528, 0.586]} rotation={[0, 0.911, 0]} scale={1.52} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.Texture} position={[1.895, 0, -1.944]} rotation={[0, -0.436, 0]} scale={[1.5, 1, 1.5]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.Texture} position={[3.423, 0, 0.005]} rotation={[-Math.PI, 1.127, -Math.PI]} scale={1.52} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.Texture} position={[3.224, 0, -0.804]} rotation={[0, -1.324, 0]} scale={1.52} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.Texture} position={[3.53, 1.834, 0.44]} rotation={[-Math.PI, 1.324, Math.PI / 2]} scale={1.52} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.Texture} position={[1.862, 1.61, -1.807]} rotation={[0, -Math.PI / 3, 0]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.Texture} position={[4.086, 2.183, 2.41]} rotation={[0, -1.548, 1.571]} scale={1.52} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Texture} position={[4.255, 0.943, 2.219]} rotation={[0, -1.002, Math.PI / 2]} scale={1.52} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.Texture} position={[4.314, 1.565, 2.343]} rotation={[Math.PI, 1.149, Math.PI / 2]} scale={[-1.52, 1.52, 1.52]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.Texture} position={[3.87, 0.315, 2.35]} rotation={[3.142, 1.526, 1.571]} scale={[-1.52, 1.52, 1.52]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.Texture} position={[3.954, 2.491, 1.607]} rotation={[0, -Math.PI / 3, 0]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.Texture} position={[-3.79, 0, 1.656]} rotation={[0, 1.393, 0]} scale={[-1.52, 1.52, 1.52]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.Texture} position={[-3.79, 1.528, 1.656]} rotation={[-Math.PI, -1.218, -Math.PI]} scale={[-1.52, 1.52, 1.52]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.Texture} position={[-3.693, 0, 2.585]} rotation={[0, -1.568, 0]} scale={1.52} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.Texture} position={[-5.36, 2.183, 0.811]} rotation={[0, 0.772, Math.PI / 2]} scale={1.52} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.Texture} position={[-5.614, 0.943, 0.817]} rotation={[0, 1.318, 1.571]} scale={1.52} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.Texture} position={[-5.564, 1.565, 0.69]} rotation={[-Math.PI, -1.171, Math.PI / 2]} scale={[-1.52, 1.52, 1.52]} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.Texture} position={[-5.257, 0.315, 1.01]} rotation={[-Math.PI, -0.795, Math.PI / 2]} scale={[-1.52, 1.52, 1.52]} />
      <mesh geometry={nodes.Object_72.geometry} material={materials.Texture} position={[-5.474, 2.794, 0.745]} rotation={[Math.PI, -1.155, Math.PI / 2]} scale={1.52} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.Texture} position={[-5.39, 4.034, 0.986]} rotation={[Math.PI, -0.609, Math.PI / 2]} scale={1.52} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.Texture} position={[-5.289, 3.412, 0.894]} rotation={[0, 0.757, Math.PI / 2]} scale={[-1.52, 1.52, 1.52]} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.Texture} position={[-5.696, 4.662, 0.718]} rotation={[0, 1.133, Math.PI / 2]} scale={[-1.52, 1.52, 1.52]} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.Texture} position={[-5.283, 0, -2.328]} rotation={[0, 0.755, 0]} scale={1.52} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.Texture} position={[-5.952, 0, -0.641]} rotation={[0, 0.953, 0]} scale={1.52} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.Texture} position={[-5.486, 0, -1.385]} rotation={[-Math.PI, -0.985, -Math.PI]} scale={1.52} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.Texture} position={[-4.476, 0, -2.749]} rotation={[-Math.PI, -0.568, -Math.PI]} scale={1.52} />
      <mesh geometry={nodes.Object_88.geometry} material={materials.Texture} position={[-3.012, 0, -3.79]} rotation={[0, 0.597, 0]} scale={1.52} />
      <mesh geometry={nodes.Object_90.geometry} material={materials.Texture} position={[-3.716, 0, -2.886]} rotation={[0, 0.644, 0]} scale={1.52} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.Texture} position={[-2.082, 0, -4.324]} rotation={[-Math.PI, -0.597, -Math.PI]} scale={1.52} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.Texture} position={[-1.016, 0, -4.489]} rotation={[0, 0.308, 0]} scale={1.52} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.Texture} position={[-0.084, 0, -5.026]} rotation={[-Math.PI, -0.039, -Math.PI]} scale={1.52} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.Texture} position={[-5.315, 1.833, -1.412]} rotation={[0, 1.062, Math.PI / 2]} scale={1.52} />
      <mesh geometry={nodes.Object_100.geometry} material={materials.Texture} position={[-4.181, 1.833, -3.064]} rotation={[-Math.PI, -0.465, -Math.PI / 2]} scale={1.52} />
      <mesh geometry={nodes.Object_102.geometry} material={materials.Texture} position={[-1.758, 1.833, -3.605]} rotation={[0, -1.165, Math.PI / 2]} scale={1.52} />
      <mesh geometry={nodes.Object_104.geometry} material={materials.Texture} position={[-0.254, 1.833, -5.542]} rotation={[0, 1.553, 1.571]} scale={1.52} />
      <mesh geometry={nodes.Object_106.geometry} material={materials.Texture} position={[-4.194, 1.836, -2.768]} rotation={[0, 0.655, Math.PI / 2]} scale={[-1.52, 1.52, 1.52]} />
      <mesh geometry={nodes.Object_108.geometry} material={materials.Texture} position={[-5.283, 2.143, -2.328]} rotation={[-Math.PI, -0.755, -Math.PI]} scale={1.52} />
      <mesh geometry={nodes.Object_110.geometry} material={materials.Texture} position={[-5.952, 2.143, -0.641]} rotation={[-Math.PI, -0.953, -Math.PI]} scale={1.52} />
      <mesh geometry={nodes.Object_112.geometry} material={materials.Texture} position={[-5.486, 2.143, -1.385]} rotation={[0, 0.985, 0]} scale={1.52} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.Texture} position={[-4.476, 2.143, -2.749]} rotation={[0, 0.568, 0]} scale={1.52} />
      <mesh geometry={nodes.Object_116.geometry} material={materials.Texture} position={[-3.012, 2.143, -3.79]} rotation={[-Math.PI, -0.597, -Math.PI]} scale={1.52} />
      <mesh geometry={nodes.Object_118.geometry} material={materials.Texture} position={[-3.727, 2.143, -3.1]} rotation={[-Math.PI, -0.644, -Math.PI]} scale={1.52} />
      <mesh geometry={nodes.Object_120.geometry} material={materials.Texture} position={[-2.082, 2.143, -4.324]} rotation={[0, 0.597, 0]} scale={1.52} />
      <mesh geometry={nodes.Object_122.geometry} material={materials.Texture} position={[-1.016, 2.143, -4.489]} rotation={[-Math.PI, -0.308, -Math.PI]} scale={1.52} />
      <mesh geometry={nodes.Object_124.geometry} material={materials.Texture} position={[-0.084, 2.143, -5.026]} rotation={[0, 0.039, 0]} scale={1.52} />
      <mesh geometry={nodes.Object_126.geometry} material={materials.Texture} position={[-5.315, 3.976, -1.412]} rotation={[0, 1.062, Math.PI / 2]} scale={1.52} />
      <mesh geometry={nodes.Object_128.geometry} material={materials.Texture} position={[-4.181, 3.976, -3.064]} rotation={[-Math.PI, -0.465, -Math.PI / 2]} scale={1.52} />
      <mesh geometry={nodes.Object_130.geometry} material={materials.Texture} position={[-1.173, 3.976, -4.449]} rotation={[0, 0.168, Math.PI / 2]} scale={1.52} />
      <mesh geometry={nodes.Object_132.geometry} material={materials.Texture} position={[-0.941, 3.976, -4.664]} rotation={[Math.PI, 0.018, -Math.PI / 2]} scale={1.52} />
      <mesh geometry={nodes.Object_134.geometry} material={materials.Texture} position={[-4.194, 3.979, -2.768]} rotation={[0, 0.655, Math.PI / 2]} scale={[-1.52, 1.52, 1.52]} />
      <mesh geometry={nodes.Object_136.geometry} material={materials.Texture} position={[-1.095, 4.291, -4.434]} rotation={[0, 0.357, 0]} />
      <mesh geometry={nodes.Object_138.geometry} material={materials.Texture} position={[-5.246, 4.291, -1.466]} rotation={[0, 1.246, 0]} />
      <mesh geometry={nodes.Object_140.geometry} material={materials.Texture} position={[5.531, 2.183, 0.174]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_142.geometry} material={materials.Texture} position={[5.786, 0.943, 0.18]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_144.geometry} material={materials.Texture} position={[5.736, 1.565, 0.053]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_146.geometry} material={materials.Texture} position={[5.428, 0.315, 0.373]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_148.geometry} material={materials.Texture} position={[5.646, 2.794, 0.107]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_150.geometry} material={materials.Texture} position={[5.562, 4.034, 0.348]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_152.geometry} material={materials.Texture} position={[5.461, 3.412, 0.256]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_154.geometry} material={materials.Texture} position={[5.868, 4.662, 0.081]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_156.geometry} material={materials.Texture} position={[4.856, 0, -2.541]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_158.geometry} material={materials.Texture} position={[5.525, 0, -0.854]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_160.geometry} material={materials.Texture} position={[5.059, 0, -1.597]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_162.geometry} material={materials.Texture} position={[4.05, 0, -2.962]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_164.geometry} material={materials.Texture} position={[2.585, 0, -4.002]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_166.geometry} material={materials.Texture} position={[3.289, 0, -3.098]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_168.geometry} material={materials.Texture} position={[1.655, 0, -4.536]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_170.geometry} material={materials.Texture} position={[0.59, 0, -4.701]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_172.geometry} material={materials.Texture} position={[4.888, 1.833, -1.624]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_174.geometry} material={materials.Texture} position={[3.754, 1.833, -3.277]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_176.geometry} material={materials.Texture} position={[1.332, 1.833, -3.817]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_178.geometry} material={materials.Texture} position={[3.767, 1.836, -2.98]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_180.geometry} material={materials.Texture} position={[4.856, 2.143, -2.541]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_182.geometry} material={materials.Texture} position={[5.525, 2.143, -0.854]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_184.geometry} material={materials.Texture} position={[5.059, 2.143, -1.597]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_186.geometry} material={materials.Texture} position={[4.05, 2.143, -2.962]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_188.geometry} material={materials.Texture} position={[2.585, 2.143, -4.002]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_190.geometry} material={materials.Texture} position={[3.3, 2.143, -3.312]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_192.geometry} material={materials.Texture} position={[1.655, 2.143, -4.536]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_194.geometry} material={materials.Texture} position={[0.59, 2.143, -4.701]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_196.geometry} material={materials.Texture} position={[4.888, 3.976, -1.624]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_198.geometry} material={materials.Texture} position={[3.754, 3.976, -3.277]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_200.geometry} material={materials.Texture} position={[0.746, 3.976, -4.662]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_202.geometry} material={materials.Texture} position={[3.767, 3.979, -2.98]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Object_204.geometry} material={materials.Texture} position={[3.198, 4.291, -3.092]} rotation={[0, -0.563, 0]} scale={[-1, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/old_computers.glb')
